import { readdir, readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";
import { lessonSchema } from "../src/content/schema.ts";

const here = dirname(fileURLToPath(import.meta.url));
const contentDir = resolve(here, "../content");
const outFile = resolve(here, "../src/content/lessons.generated.ts");

export async function buildLessons() {
  const files = (await readdir(contentDir)).filter((f) => /day\d{2}\.md$/.test(f)).sort();
  const lessons = [];
  for (const file of files) {
    const raw = await readFile(resolve(contentDir, file), "utf8");
    const { data } = matter(raw);
    lessons.push(lessonSchema.parse(data));
  }
  return lessons;
}

async function main() {
  const lessons = await buildLessons();
  const banner = "// GENERATED by scripts/generate-content.mjs — do not edit.\n";
  const body = `import type { Lesson } from "./schema";\nexport const lessons: Lesson[] = ${JSON.stringify(lessons, null, 2)} as const;\n`;
  await writeFile(outFile, banner + body, "utf8");
  console.log(`generate-content: wrote ${lessons.length} lessons`);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
